### DISCUSSION TITLE
AttributeError: 'PandasDatasource' object has no attribute 'get_batch_list_from_batch_request'

### DISCUSSION THREAD

**Discussion by ghost** [great-expectations/great_expectations#10461] [Support]
I am getting an run time error while Executing the code. 

```python
import pandas as pd
from pymongo import MongoClient
import great_expectations as ge
context = ge.get_context()
from great_expectations.core.batch import RuntimeBatchRequest
 
# MongoDB client setup
client = MongoClient("link to mongoclient")
db = client[' Db name']
collection = db['collection name']
 
# Fetch data from MongoDB and convert it to a DataFrame
data = list(collection.find())
df = pd.DataFrame(data)
 
# Debugging: Check the contents and structure of the DataFrame
if df.empty:
    raise ValueError("The DataFrame is empty. Please check the MongoDB collection.")
 
# Print DataFrame structure
print("DataFrame head:")
print(df.head())
 
# Check if the required column exists
if 'bill_of_entry_number' not in df.columns:
    raise ValueError("'bill_of_entry_number' column is missing in the DataFrame.")
 
# Initialize DataContext with your Great Expectations directory path
context = ge.data_context.DataContext("/Users/apple/Documents/PythonNew/gx/")
 
# Create a RuntimeBatchRequest for the DataFrame
batch_request = RuntimeBatchRequest(
    datasource_name="my_pandas_datasource",  # Ensure this matches your great_expectations.yml
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="default_name",  # You can name this whatever makes sense
    runtime_parameters={"batch_data": df},
    batch_identifiers={"default_identifier_name": "batch_001"}
)
 
# Create a Validator
validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name="exim_cargo_expectations"  # Ensure you have this expectation suite
)
 
# Check if the batch is correctly assigned
if validator.active_batch is None:
    raise ValueError("Validator's active batch is None. Check batch assignment.")
 
# Defining expectations
# Expect the values in the 'bill_of_entry_number' column to be greater than 0
validator.expect_column_values_to_be_greater_than('bill_of_entry_number', 0)
 
# Running validations
results = validator.validate()
 
# Printing results
print("Validation results:")
print(results)
```
 

and the configuration file looks like this 

```yaml
# Welcome to Great Expectations! Always know what to expect from your data.
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources:
  my_pandas_datasource:
    class_name: PandasDatasource
    module_name: great_expectations.datasource
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
    data_asset_type:
      class_name: PandasDataset
      module_name: great_expectations.dataset
config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: xxxxxxxxxxxxxxx
  enabled: true
notebooks:
include_rendered_content:
  globally: false
  expectation_suite: false
  expectation_validation_result: false
```
<img width="851" alt="Screenshot 2024-10-03 at 10 38 30 AM" src="https://github.com/user-attachments/assets/8165f812-0d13-499b-8586-f66cbfe76c2b">

error is AttributeError: 'PandasDatasource' object has no attribute 'get_batch_list_from_batch_request'.
