### DISCUSSION TITLE
Validations of Snowflake table fails on create temp table when schema is not defined in the datasource

### DISCUSSION THREAD

**Discussion by razido1** [great-expectations/great_expectations#5342] [Support]
Running validation on Snowflake table fails on 
**(snowflake.connector.errors.ProgrammingError) 090106 (22000): Cannot perform CREATE TEMPTABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.**

We have dynamic schemas and work with several schemas, so cannot define the schema in the datasource, and when trying to run the expectation,we get the above error.
Looking at [this](https://githubmemory.com/repo/great-expectations/great_expectations/issues/3459) discussion, a workaround was suggested to not create a temp table, but as you can see below, I tried this but still getting the same error.

Here is the execution engine configuration (no schema):
```
snowflake_db:
    execution_engine:
      create_temp_table: False
      credentials:
        host: ***
        username: ***
        database: ***
        query:
          warehouse: WH_LARGE_POOL
          role: ***
        password: ***
        drivername: snowflake
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
    module_name: great_expectations.datasource
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        include_schema_name: true
        class_name: InferredAssetSqlDataConnector

```

And here is the Checkpoint validatoin configuration:
```
validations:
  - batch_request:
      datasource_name: snowflake_db
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: my_schema.my_table
      data_connector_query:
        index: -1

```
I am using great_expectation v 0.15.10
