### DISCUSSION TITLE
Can I use duckdb?

### DISCUSSION THREAD

**Discussion by chinahamu** [great-expectations/great_expectations#6932] [Support]
This is how CONNECTION is set up.

```
datasources:
  duckbd:
    class_name: Datasource
    execution_engine:
      connection_string: duckdb:///../../../db/test.duckdb
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        include_schema_name: true
        introspection_directives:
          schema_name: main
        module_name: great_expectations.datasource.data_connector
      default_configured_data_connector_name:
        class_name: ConfiguredAssetSqlDataConnector
        assets:
          oders:
            class_name: Asset
            schema_name: main
            module_name: great_expectations.datasource.data_connector.asset
        module_name: great_expectations.datasource.data_connector
    module_name: great_expectations.datasource
config_variables_file_path: uncommitted/config_variables.yml
```

Success in test_yaml_config

`context.test_yaml_config(yaml_config=example_yaml)
`

However, when I try to run checkpoint, initialize fails.

`great_expectations --v3-api checkpoint run my_checkpoint`

```
Using v3 (Batch Request) API
Cannot initialize datasource duckbd: Cannot initialize datasource duckbd, error: (duckdb.IOException) 
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Cannot initialize datasource duckbd, error: The given datasource could not be retrieved from the DataContext; please confirm that your configuration is accurate.
```

Is it not supported in the first place?

my_checkpoint

```
name: my_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my-run-name-template'
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: duckbd
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: main.customers
      data_connector_query:
        index: -1
    expectation_suite_name: my_first_suite
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:

```
