### ISSUE TITLE
how to append multiple validation results in a doc site

### ISSUE THREAD

**Issue by valentinenkemka** [great-expectations/great_expectations#10017]
I am following the instructions in https://legacy.017.docs.greatexpectations.io/docs/0.15.50/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery/#part-1-local-configuration-of-great-expectations-that-connects-to-google-cloud-platform

and used this for doc site configuration
```# Define data docs site configuration
data_docs_sites = {
    "doc_wesite": {
        "class_name": "SiteBuilder",
        "store_backend": {
            "class_name": "TupleGCSStoreBackend",
            "project": project_id,
            "bucket": gcs_bucket
        },
        "site_index_builder": {
            "class_name": "DefaultSiteIndexBuilder"
        }
    }
}```

With the above settings, I only get  the latest validation results in the doc site in GCS bucket. I would like to write multiple validation results in the same site on GCS

**Comment by rubnsbarbosa** [comment]
Following the documentation we need to set up 3 different buckets to store: expectations, validations and data docs sites. 

Be aware: your validations results on GCS will be stored in the bucket that you should create and configure in the section below
```yml
stores:
  validations_GCS_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleGCSStoreBackend
      project: <your_project_id>
      bucket: <your_bucket_name>
      prefix: <your_prefix_name>

validations_store_name: validations_GCS_store
```
You can write multiple expectations as you like and use the validator object to save them. The validation results that you see on the GCS data documents website are created based on the validation results that were stored in the bucket that you created and configured as in the example above.
