### ISSUE TITLE
GX checkpoint processing in Spark appears to exit without completion - errors are buried in validation results

### ISSUE THREAD

**Issue by carygeo** [great-expectations/great_expectations#10151]
**Describe the bug**
When running a checkpoint in spark, when there are errors or issues in a schema GX does not reach 100% progress bar and no logging details are issued in terms of the errors / warnings. To the user it looks as though the checkpoint located my expectations, attempts to run but only makes it rough halfway and exits skipping all spark jobs / stages without any completion or errors.   This is similar to latent bug/defect although intentional in this case since you want the remaining processing to still take place rather than stop all processing.  It is important that the user knows this is happening when monitoring in python.

This is key to users who do not only rely on the HTML data docs for feedback but instead parse validation results output to determine success or failure. 

**To Reproduce**
Load a table that does not have all the columns for the expectation_suite in the checkpoint you intend to run.

Checkpoint:
```
{
  "action_list": [
    {
      "name": "update_data_docs",
      "action": {
        "class_name": "UpdateDataDocsAction"
      }
    }
  ],
  "batch_request": {
    "datasource_name": "memory_datasource",
    "data_asset_name": "complex",
    "options": {}
  },
  "class_name": "Checkpoint",
  "config_version": 1.0,
  "evaluation_parameters": {},
  "expectation_suite_name": "complex",
  "module_name": "great_expectations.checkpoint",
  "name": "checkpoint_complex",
  "profilers": [],
  "run_name_template": "%Y%m%d-%H%M%S-my-run-name-template",
  "runtime_configuration": {
    "result_format": {
      "result_format": "COMPLETE",
      "unexpected_index_column_names": [
        "point_id"
      ],
      "return_unexpected_index_query": true
    }
  },
  "validations": []
}
```

gx.yml
```
config_version: 3
datasources: {}
config_variables_file_path: uncommitted/config_variables.yml
plugins_directory: plugins/
stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/
  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/
  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/
  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/
expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store
data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
anonymous_usage_statistics:
  enabled: true
  ```

**Expected behavior**
- Progress bar should indicate that it finished but with another color perhaps
- Warnings or errors from “exception_info” saved into the validation results from the checkpoint run should be logged as INFO for the user
- Demonstrate what the GX checkpoint run is processing and what issues it encounters.

**Environment (please complete the following information):**
- Databricks / Spark
 - Great Expectations Version:
import great_expectations as ge
print(ge.version)
→ 0.18.19

 - Data Source: Delta Tables
 - Cloud environment: Databricks

**Additional context**
In general, beyond this specific errors described, more logging INFO should help the user know what processing is taking place in the GX checkpoint run step.  This would help people understand performance issues or troubleshooting steps.

See --> https://discourse.greatexpectations.io/t/great-expectations-checkpoint-quits-without-error/1815
