### ISSUE TITLE
Issue in Slack notifications

### ISSUE THREAD

**Issue by masfworld** [great-expectations/great_expectations#10313]
**Describe the bug**
GX returns an error trying to send a Slack notifications.
```
  File "/Users/miguel/code/data_integrity/venv/lib/python3.12/site-packages/great_expectations/core/expectation_validation_result.py", line 522, in asset_name
    return self.meta["active_batch_definition"].data_asset_name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'data_asset_name'
```

**To Reproduce**
`great_expectations.yml`
```
config_version: 4.0
fluent_datasources:
  pg_api_datasource_readonly:
    type: postgres
    connection_string: postgresql+psycopg2://data_integrity:${XXX}@host.docker.internal:5432/api
  sf_api_datasource:
    type: snowflake
    connection_string: 
      snowflake://DATA_INTEGRITY_PROD:${DATA_INTEGRITY_SF_PASS}@XXX/XXX/XXX?warehouse=LOAD_AND_TRANSFORM&role=CORE_API_SENSITIVE_DATA_ACCESS&application=great_expectations_oss
config_variables_file_path: uncommitted/config_variables.yml
plugins_directory: plugins/
stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: ./var/data/expectations/
  validation_results_store:
    class_name: ValidationResultsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/
  checkpoint_store:
    class_name: CheckpointStore
  validation_definition_store:
    class_name: ValidationDefinitionStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: ./validation_definitions/
expectations_store_name: expectations_store
checkpoint_store_name: checkpoint_store
validation_results_store_name: validation_results_store
data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: ./var/data/uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

**Expected behavior**
Slack notifiaction should be sent

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 1.0.0
 - Data Source: Pandas, PostgreSQL and Snowflake
 - Cloud environment: Local laptop

**Additional context**
Code returning the error:
```
# Create a validation
    validation_name = "_".join(['bmy_validation_definition',date_time])
    validation_definition = context.validation_definitions.add(
        gx.ValidationDefinition(
            data=batch_definition_merge, suite=suite, name=validation_name, 
        )
    )
    
    # Create the Checkpoint
    checkpoint_name = "_".join(['my_checkpoint_name',date_time])
    print(f'Validation Definition: {validation_definition}')
    checkpoint = gx.Checkpoint(
        name=checkpoint_name,
        validation_definitions=[validation_definition],
        actions=getActionLists(),
        result_format={"result_format": "COMPLETE"},
    )
    
    # Save the Checkpoint to the Data Context
    context.checkpoints.add(checkpoint)
    
    # merged_data is a Pandas Dataframe
    checkpoint.run(
        batch_parameters={"dataframe": merged_data}
    )
    
    context.build_data_docs()

def getActionLists():
    slack_webhook = os.getenv('SLACK_WEBHOOK', None)
    if not slack_webhook:
        return []
    
    return [
        # This Action sends a Slack Notification if an Expectation fails.
        gx.checkpoint.SlackNotificationAction(
            name="send_slack_notification_on_failed_expectations",
            slack_webhook=slack_webhook,
            notify_on="all",
            show_failed_expectations=False
        ),
        # This Action updates the Data Docs static website with the Validation
        #   Results after the Checkpoint is run.
        gx.checkpoint.UpdateDataDocsAction(
            name="update_all_data_docs",
        ),
    ]
```
More info in this [Slack thread](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1724832931078659)
