### ISSUE TITLE
BUG: entire dataframe ending up in validation results JSON

### ISSUE THREAD

**Issue by jschra** [great-expectations/great_expectations#10327]
**Describe the bug**
Using GX 1.0.1 with an in-memory pandas data source and related asset and batch definition, whenever I run an expectation suite over in-memory data passed via said data source and asset, the entire dataframe ends up in the validation result JSON in the meta section under keys ["active_batch_definition"]["batch_identifiers"]["dataframe"], which in my eyes is data leakage. The validation JSON should only contain results related to the validation and some meta data, but never the original data. 

**To Reproduce**
To reproduce the error using GX 1.0.1, I have added mock data to this issue. Please find below (1) the logic I run and (2) the GX yaml file, although it is not necessary as it is the default one that gets created by the logic of the script

setup_gx.py
```python
import great_expectations as gx
import pandas as pd

# -- Set GX constants for artifact creation
NAME_DATA_SOURCE = "pandas"
NAME_DATA_ASSET = "tutorial_data"
NAME_BATCH_DEF = "pandas_tutorial"
NAME_EXPECTATION_SUITE = "tutorial"
NAME_VALIDATION_DEF = "pandas-validation"
NAME_CHECKPOINT = "pandas"

# -- Load data for configuration
FILE_CONFIGURE = "data/yellow_tripdata_2021-11.csv"
df_configure = pd.read_csv(FILE_CONFIGURE)

# -- 1. Initialize GX for configuration
context = gx.get_context(mode="file")

data_source = context.data_sources.add_pandas(name=NAME_DATA_SOURCE)
data_asset = data_source.add_dataframe_asset(name=NAME_DATA_ASSET)
batch_definition = data_asset.add_batch_definition_whole_dataframe(NAME_BATCH_DEF)

# -- 2. Configure expectation suite to be called over runtime data later
expectation_suite = gx.ExpectationSuite(name=NAME_EXPECTATION_SUITE)
expectation_suite = context.suites.add(expectation_suite)

# -- 2.1. Define table level expectations
columns = list(df_configure.columns)
expectation = gx.expectations.ExpectTableColumnsToMatchSet(column_set=columns)
expectation_suite.add_expectation(expectation)

# -- 2.2. Define column level expectations
expectation = gx.expectations.ExpectColumnValuesToNotBeNull(column="VendorID")
expectation_suite.add_expectation(expectation)

expected_values = [1, 2]
expectation = gx.expectations.ExpectColumnValuesToBeInSet(
    column="VendorID", value_set=expected_values
)
expectation_suite.add_expectation(expectation)

# -- 2.3. Evaluate results on test dataset
batch_parameters = {"dataframe": df_configure}
batch = batch_definition.get_batch(batch_parameters=batch_parameters)
validation_results = batch.validate(expectation_suite)

# -- 3. Bundle suite and batch into validation definition and checkpoint w/ bundled
# --    actions for easy execution later
validation_definition = gx.ValidationDefinition(
    data=batch_definition, suite=expectation_suite, name=NAME_VALIDATION_DEF
)
validation_definition = context.validation_definitions.add(validation_definition)

action_list = [
    gx.checkpoint.UpdateDataDocsAction(
        name="update_all_data_docs",
    ),
]
checkpoint = gx.Checkpoint(
    name=NAME_CHECKPOINT,
    validation_definitions=[validation_definition],
    actions=action_list,
    result_format={
        "result_format": "COMPLETE",
    },
)
context.checkpoints.add(checkpoint)

# -- 4. Run checkpoint to validate if everything works properly
runid = gx.RunIdentifier(run_name="Configuration run")
results = checkpoint.run(batch_parameters=batch_parameters, run_id=runid)
```
great_expectations.yml
```
# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 4.0

# This config file supports variable substitution which enables: 1) keeping
# secrets out of source control & 2) environment-based configuration changes
# such as staging vs prod.
#
# When GX encounters substitution syntax (like `my_key: ${my_value}` or
# `my_key: $my_value`) in the great_expectations.yml file, it will attempt
# to replace the value of `my_key` with the value from an environment
# variable `my_value` or a corresponding key read from this config file,
# which is defined through the `config_variables_file_path`.
# Environment variables take precedence over variables defined here.
#
# Substitution values defined here can be a simple (non-nested) value,
# nested value such as a dictionary, or an environment variable (i.e. ${ENV_VAR})
#
#
# https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials


config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validation_results_store:
    class_name: ValidationResultsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  validation_definition_store:
    class_name: ValidationDefinitionStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: validation_definitions/

expectations_store_name: expectations_store
validation_results_store_name: validation_results_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

analytics_enabled: true
fluent_datasources:
  pandas:
    type: pandas
    id: 8aa2879f-d6d8-426e-8e81-0c191c22855e
    assets:
      tutorial_data:
        type: dataframe
        id: 8cea57b7-0178-4bd0-8054-c9f43429dd52
        batch_metadata: {}
        batch_definitions:
          pandas_tutorial:
            id: 8a5753fa-d227-4d4a-a5b4-cb61ffacb946
            partitioner:
data_context_id: ea5099b6-79ea-4de8-a1f5-180b722d64a1
```

**Expected behavior**
I would expect that the contents of the dataframe would not end up in the validation JSON or at least would be redacted, as is already applied in the batch_parameters section. I will create a PR for a possible fix which mimicks the behavior used for batch_parameters later.

EDIT* proposed PR for fix: https://github.com/great-expectations/great_expectations/pull/10328

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 1.0.1
 - Data Source: Pandas
 - Cloud environment: N/A

**Additional context**
None at this time

[yellow_tripdata_2021-11.csv](https://github.com/user-attachments/files/16849664/yellow_tripdata_2021-11.csv)
