### ISSUE TITLE
Improve OpenSSF Scorecard Report - remove critical issue by changing pr-title-checker.yml CI workflow

### ISSUE THREAD

**Issue by nils-woxholt** [great-expectations/great_expectations#10607]
**Describe the bug**
Noticed when viewing the OpenSSF scorecard for the Great Expectations library at:
https://scorecard.dev/viewer/?uri=github.com/great-expectations/great_expectations

There is a critical *Dangerous-Workflow* pattern detected - the error is as follows:

> Warn: script injection with untrusted input ' github.event.pull_request.title ': .github/workflows/pr-title-checker.yml:17

The workflow checks passes the pull_request.title value to a script command, which introduces a possible script injection issue.

**To Reproduce**
The issue is in the github workflow in this file:
- https://github.com/great-expectations/great_expectations/blob/develop/.github/workflows/pr-title-checker.yml

**Expected behavior**

To avoid the OpenSSF warning about script injection in the pull_request.title value, we could use GitHub Actions' built-in if condition to validate the PR title. This approach avoids using shell commands that could be vulnerable to injection attacks. Here's a revised version of the workflow:

```
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title validity
        if: "!contains(github.event.pull_request.title, '[FEATURE]') && !contains(github.event.pull_request.title, '[BUGFIX]') && !contains(github.event.pull_request.title, '[DOCS]') && !contains(github.event.pull_request.title, '[MAINTENANCE]') && !contains(github.event.pull_request.title, '[CONTRIB]') && !contains(github.event.pull_request.title, '[RELEASE]')"
        run: |
          echo "Invalid PR title - please prefix with one of: [FEATURE] | [BUGFIX] | [DOCS] | [MAINTENANCE] | [CONTRIB] | [RELEASE]"
          exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This version uses the `if` condition to check if the PR title contains any of the accepted prefixes. If none of the prefixes are found, it outputs an error message and exits with a status of 1. 

This approach mitigates the risk of script injection by avoiding the use of shell commands to process the PR title.

**Environment (please complete the following information):**
 - Operating System: any
 - Great Expectations Version: 1.2.0
 - Data Source: n/a
 - Cloud environment: n/a

**Additional context**

- https://github.com/ossf/scorecard/blob/367426ed5d9cc62f4944dc4a2174f3bbb5e22169/docs/checks.md#dangerous-workflow
- https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
