### ISSUE TITLE
Cannot render validations section of Data Docs

### ISSUE THREAD

**Issue by niewol-pixel** [great-expectations/great_expectations#10739]
**Describe the bug**
In my project I wrote a function to update the data docs of my great expectations project. The function is as follows: 

```python
def update_data_docs(context: FileDataContext) -> None:
    site_config = {
        "class_name": "SiteBuilder",
        "site_index_builder": {"class_name": "DefaultSiteIndexBuilder"},
        "store_backend": {
            "class_name": "TupleFilesystemStoreBackend",
            "base_directory": "uncommitted/data_docs/local_site/",
        },
    }
    site_name = "mygx"
    try:
        context.update_data_docs_site(site_name, site_config)
    except InvalidKeyError:
        context.add_data_docs_site(site_name=site_name,
                                   site_config=site_config)
    context.build_data_docs()
```

When I try to update an existing site "mygx", I cannot render the 'validations' section on my site, even though this is a pretty similar set-up to the documentation. 

**To Reproduce**
Please include your great_expectations.yml config, the code you’re executing that causes the issue, and the full stack trace of any error(s).

great_expectations.yml:
```yaml
# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 4.0

# This config file supports variable substitution which enables: 1) keeping
# secrets out of source control & 2) environment-based configuration changes
# such as staging vs prod.
#
# When GX encounters substitution syntax (like `my_key: ${my_value}` or
# `my_key: $my_value`) in the great_expectations.yml file, it will attempt
# to replace the value of `my_key` with the value from an environment
# variable `my_value` or a corresponding key read from this config file,
# which is defined through the `config_variables_file_path`.
# Environment variables take precedence over variables defined here.
#
# Substitution values defined here can be a simple (non-nested) value,
# nested value such as a dictionary, or an environment variable (i.e. ${ENV_VAR})
#
#
# https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials


config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validation_results_store:
    class_name: ValidationResultsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  validation_definition_store:
    class_name: ValidationDefinitionStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: validation_definitions/

expectations_store_name: expectations_store
validation_results_store_name: validation_results_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
  bkrgx:
    class_name: SiteBuilder
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
fluent_datasources:
  afas_data_source:
    type: spark
    id: 16977468-a8e1-418a-ab06-1b7a5cee4b6d
    assets:
      branches_dataframe_data_asset:
        type: dataframe
        id: e3602234-3801-46f6-be40-d688e2b321f4
        batch_metadata: {}
        batch_definitions:
          branches_batch_definition:
            id: 850d2e7e-142b-45c3-8694-e735aad654df
            partitioner:
  gestandaardiseerd_data_source:
    type: spark
    id: 9f6bb7b9-c820-497b-9b14-72b72d6e9381
    assets:
      afas_branches_dataframe_data_asset:
        type: dataframe
        id: 5c96188c-9952-427a-8875-3b1144ebf85f
        batch_metadata: {}
        batch_definitions:
          afas_branches_batch_definition:
            id: 5815a4fc-7793-4ae1-9174-ab63a24cdfcb
            partitioner:
      afas_verkooprelatie_dataframe_data_asset:
        type: dataframe
        id: c2e29668-5f6d-44c9-b481-eda9fd5b3f0c
        batch_metadata: {}
        batch_definitions:
          afas_verkooprelatie_batch_definition:
            id: 58907bcc-db9a-4b10-bc7e-37900b398356
            partitioner:
analytics_enabled:
data_context_id: 655338a7-0f2f-41b7-878a-45c067dca00e
```

The code I execute:
```python
def update_data_docs(context: FileDataContext) -> None:
    site_config = {
        "class_name": "SiteBuilder",
        "site_index_builder": {"class_name": "DefaultSiteIndexBuilder"},
        "store_backend": {
            "class_name": "TupleFilesystemStoreBackend",
            "base_directory": "uncommitted/data_docs/local_site/",
        },
    }
    site_name = "mygx"
    try:
        context.update_data_docs_site(site_name, site_config)
    except InvalidKeyError:
        context.add_data_docs_site(site_name=site_name,
                                   site_config=site_config)
    context.build_data_docs()

context = gx.get_context(mode="file", project_root_dir=project_root_dir)
update_data_docs(context)
```

Full stack trace:
```
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                KeyError: "'run_id'".  Traceback: "Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/great_expectations/render/renderer/site_builder.py", line 460, in build
    rendered_content = self.renderer_class.render(resource)
  File "/usr/local/lib/python3.10/site-packages/great_expectations/render/renderer/page_renderer.py", line 78, in render
    run_name, run_time = self._parse_run_values(validation_results)
  File "/usr/local/lib/python3.10/site-packages/great_expectations/render/renderer/page_renderer.py", line 136, in _parse_run_values
    run_id: Union[str, dict, RunIdentifier] = validation_results.meta["run_id"]
KeyError: 'run_id'
".
```

**Expected behavior**
I expect to be able to render the 'Validation Results' section of my Data Docs by using `context.build_data_docs()`.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 1.2.4
 - Data Source: [e.g. Pandas, Snowflake]
 - Cloud environment: Azure

**Additional context**
Opening up page_renderer.py shows the following lines around line 136:
```python
    def _parse_run_values(
        self, validation_results: ExpectationSuiteValidationResult
    ) -> Tuple[str, str]:
        run_id: Union[str, dict, RunIdentifier] = validation_results.meta["run_id"]
        if isinstance(run_id, str):
            try:
                run_time = parse(run_id).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
            except (ValueError, TypeError):
                run_time = "__none__"
            run_name = run_id
```

printing 'validation_results.meta' indeed does not show the key "run_id", but it does show the key "id". However, when I replace "run_id" with "id", I still receive the same error (but for "id"), as if it weren't a key.

If I replace the dictionary lookup here (and in line 414 in the _render_validation_info class method) with a regular string, like "cool_run_id", then my page renders, but my 'Run Name' column only contains __none__ values.

Could it have something to do with my validations? I run my validations as follows:
```python
validation_definition_name = f"{entiteit}_{laag}_validation_definition"

    try:
        validation_definition = context.validation_definitions.get(validation_definition_name)
    except DataContextError:
        validation_definition = ValidationDefinition(
            data=batch_definition, suite=expectation_suite, name=validation_definition_name
        )
        validation_definition = context.validation_definitions.add(validation_definition)

validation_results = validation_definition.run(batch_parameters=batch_parameters)
```

I leave the `run_id` argument empty, as is recommended in the documentation:

run_id
An identifier for this run. Typically, this should be set to None and it will be generated by this call.
