### ISSUE TITLE
Data Docs host on S3 cannot redirect to other pages due to access denied

### ISSUE THREAD

**Issue by marxaem** [great-expectations/great_expectations#10775]
**Describe the bug**
I am trying to host and share Data Docs on AWS S3. After `checkpoint.run()`, an index.html file on S3 was generated as expected.  I followed the instruction to configure bucket policy as guided in [Host and share Data Docs](https://docs.greatexpectations.io/docs/0.18/oss/guides/setup/configuring_data_docs/host_and_share_data_docs/) but when I opened the index.html from my bucket and clicked on any run record, it couldn't redirect to the detailed validation results page, it gave an Access Denied error. This problem is similar to an old issue [Data Docs > S3 > Links to runs are access Denied](https://github.com/great-expectations/great_expectations/issues/1235) but in a different version of GX.

**To Reproduce**
The data docs site configurations are as follows
```yaml
data_docs_sites:
  S3_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: bucket-name
      prefix: data-docs/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

By clicking index.html in S3 bucket, the Data Docs link will look like:
`https://bucket-name.s3.ap-southeast-1.amazonaws.com/data-docs/index.html?X-Amz-Algorithm=xxx&...`
However, when I clicked the run record, those keys generated from AWS were not following resulting in an Access Denied.
`https://bucket-name.s3.ap-southeast-1.amazonaws.com/data-docs/expectations/my_suite.html`

**Expected behavior**
Data Docs hosted on AWS S3 can be clicked to redirect to each page inside.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 1.1.0
 - Data Source: Spark dataframe
 - Cloud environment: AWS
