### ISSUE TITLE
Error Instantiating ValidationResultsStore with Postgres Backend in Great Expectations v1.0.6 on Azure Databricks

### ISSUE THREAD

**Issue by MidnightRambo** [great-expectations/great_expectations#10803]
### **Description**
We are experiencing an issue with the `ValidationResultsStore` when configuring Great Expectations (GE) version **1.0.6** to use a Postgres backend within an **Azure Databricks** environment (Runtime version **14.3**). After upgrading from GE version **0.18.4**, where we successfully used Postgres as an external metric store, the system fails to instantiate the `ValidationResultsStore`, despite the Postgres connection being functional.

---

### **Steps to Reproduce**

1. **Environment Setup:**
   - **Platform:** Azure Databricks (Runtime version 14.3)
   - **Great Expectations Version:** 1.0.6
   - **Postgres Version:** 1.0.6
   - **Metric Store:** Postgres used as an external metric store
   - **Visualization Tool:** Grafana for dashboards

2. **Configuration:**
   - Updated GE configuration from version 0.18.4 to 1.0.6.
   - Rewrote data quality tests to be compatible with the new GE version.
   - Configured the `data_context.yml` with multiple stores:

     **Expectations Store:**
     ```yaml
     expectations_store:
       class_name: ExpectationsStore
       store_backend:
         class_name: TupleFilesystemStoreBackend
         base_directory: expectations/
     ```

     **Validation Results Store:**
     ```yaml
     validation_results_store:
       class_name: ValidationResultsStore
       store_backend:
         class_name: DatabaseStoreBackend
         credentials: ${db_creds}
     ```

3. **Execution:**
   - Ran data quality tests successfully.
   - Attempted to write validation results to the Postgres store.

4. **Error Encountered:**
   - Received a `ClassInstantiationError`:
     ```
     ClassInstantiationError: Module great_expectations.data_context.store exists, but the system is unable to create an instance of the class ValidationResultsStore within this module.
     Please make sure that the class named ValidationResultsStore is properly defined inside its intended module and declared correctly by the calling entity.
     This error is unrecoverable.
     ```

---

### **Expected Behavior**
Great Expectations should successfully instantiate the `ValidationResultsStore` using the Postgres backend, allowing validation results to be written to the external Postgres metric store without errors.

---

### **Actual Behavior**
Upon attempting to instantiate the `ValidationResultsStore` with the Postgres backend, GE throws a `ClassInstantiationError`, indicating it cannot create an instance of `ValidationResultsStore` within the `great_expectations.data_context.store` module.

---

### **Environment**

- **Great Expectations Version:** 1.0.6
- **Databricks Runtime:** 14.3
- **Operating System:** Azure Databricks (manylinux x86)

---

### **Additional Context**

- The Postgres connection is verified to be working outside of Great Expectations.
- The configuration for `ValidationResultsStore` mirrors the previous setup from GE version 0.18.4.
- No relevant information found in the official Great Expectations documentation regarding configuring `ValidationResultsStore` with an external Postgres store in the newer version.
- Environmental variables for database credentials are correctly set and accessible within Databricks.

---

### **Possible Solution** *(Optional)*
If there have been changes to the class names, module paths, or configuration structure in GE version 1.0.6 related to store backends, please provide updated documentation or examples to assist in correctly setting up the `ValidationResultsStore` with a Postgres backend.
