### ISSUE TITLE
result_format = "COMPLETE" does not work

### ISSUE THREAD

**Issue by Max-Bld** [great-expectations/great_expectations#10914]
**Describe the bug**

I want to get all the rows indexes which have a null value in any column. I therefore use the `ExpectColumnValuesToNotBeNull` expectation, with the parameter `result_format = "COMPLETE"` for each column in an Expectation Suite.

But neither the field `unexpected_index_list`,  or `unexpected_index_query`, appear in the validation results JSON.

Data comes from a local PostgreSQL database.

**To Reproduce**
great_expectations.yml:

```yml
config_version: 4.0

config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validation_results_store:
    class_name: ValidationResultsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  validation_definition_store:
    class_name: ValidationDefinitionStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: validation_definitions/

expectations_store_name: expectations_store
validation_results_store_name: validation_results_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
fluent_datasources:
  postgres_datatourisme_database:
    type: sql
    id: c7bd8536-5e7d-4555-9e22-71081ee4bb82
    assets:
      datatourisme_data_table:
        type: table
        id: 6d88f036-a7f1-4883-8b53-0344d8a02508
        batch_metadata: {}
        batch_definitions:
          whole_table_batch:
            id: ff646271-b7a1-4981-938b-59fc3f3857f1
            partitioner:
        table_name: raw.datatourisme_data
        schema_name:
    connection_string: postgresql://postgres:mysecret@localhost:5432
analytics_enabled:
data_context_id: 18c04598-a5c6-4baf-ba95-8d530d254a90

```

 The code:

```python
context = gx.get_context(mode="file")

data_source_name = "postgres_datatourisme_database"

data_source = context.data_sources.add_or_update_sql(
    name=data_source_name, 
    connection_string=connection_string
    )

data_asset_name = f"{table_name}_table"

data_asset = data_source.add_table_asset(
    table_name=f"raw.{table_name}", 
    name=data_asset_name
)

batch_definition_name = "whole_table_batch"

batch_definition = data_asset.add_batch_definition_whole_table(
    name=batch_definition_name
)

suite_name = "completeness_suite"

suite = gx.ExpectationSuite(
    name=suite_name
)

expectations = []

for column in column_names:

    expectation = gxe.ExpectColumnValuesToNotBeNull(
        column=column,
        result_format="COMPLETE"
    )

    suite.add_expectation(expectation)

context.suites.add_or_update(suite)

context.suites.get(name=suite_name)

batch_definition = (
    context.data_sources.get(data_source_name)
    .get_asset(data_asset_name)
    .get_batch_definition(batch_definition_name)
)

expectation_suite = context.suites.get(name=suite_name)

validation_definition_name = "completeness_validation_definition"
validation_definition = gx.ValidationDefinition(
    data=batch_definition, suite=expectation_suite, name=definition_name
)

validation_results = validation_definition.run()
```

Validation results JSON : 

```json
{
  "success": false,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "id"
        },
        "meta": {},
        "id": "dca395b3-ba80-43e3-a877-c1b29f59243f"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "nom_du_poi"
        },
        "meta": {},
        "id": "ad450c76-fbaa-411d-8b82-eb284b498e02"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "categories_de_poi"
        },
        "meta": {},
        "id": "2ba1c76d-0e92-4fdf-8e9f-2153988bcc4f"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "latitude"
        },
        "meta": {},
        "id": "8a541ea2-4e0c-4187-a186-67b5d01fddef"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "longitude"
        },
        "meta": {},
        "id": "35b78f4a-feeb-4211-b188-5123febbe95c"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "adresse_postale"
        },
        "meta": {},
        "id": "c718482f-441e-4488-a753-b593b92ec0bc"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 46018,
        "unexpected_percent": 9.636490422771752,
        "partial_unexpected_list": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        "partial_unexpected_counts": [
          {
            "value": null,
            "count": 20
          }
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "code_postal_et_commune"
        },
        "meta": {},
        "id": "ee4a6470-79b3-42db-a07b-f73228ec7585"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "periodes_regroupees"
        },
        "meta": {},
        "id": "9b360b21-b04d-481c-a236-2022a5a17aa3"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 398907,
        "unexpected_percent": 83.53391031936658,
        "partial_unexpected_list": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        "partial_unexpected_counts": [
          {
            "value": null,
            "count": 20
          }
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "covid19_mesures_specifiques"
        },
        "meta": {},
        "id": "76aaff86-34f3-490c-b17e-296e39ebe9b7"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 469979,
        "unexpected_percent": 98.41688322838553,
        "partial_unexpected_list": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        "partial_unexpected_counts": [
          {
            "value": null,
            "count": 20
          }
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "createur_de_la_donnee"
        },
        "meta": {},
        "id": "1286f750-0383-4a2f-aa81-5951241f255b"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "sit_diffuseur"
        },
        "meta": {},
        "id": "28e656e8-6fbf-49cf-99fe-760c01b724ec"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "date_de_mise_a_jour"
        },
        "meta": {},
        "id": "a446a60d-d753-43bc-8542-7337ce671795"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "contacts_du_poi"
        },
        "meta": {},
        "id": "b94171d3-7e48-47be-ad8e-9c7645c59955"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 14717,
        "unexpected_percent": 3.0818425301389,
        "partial_unexpected_list": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        "partial_unexpected_counts": [
          {
            "value": null,
            "count": 20
          }
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "classements_du_poi"
        },
        "meta": {},
        "id": "f2df11ec-2004-4cf7-a8ce-837b649cff34"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 387610,
        "unexpected_percent": 81.16823966210089,
        "partial_unexpected_list": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        "partial_unexpected_counts": [
          {
            "value": null,
            "count": 20
          }
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "description"
        },
        "meta": {},
        "id": "59f20fa1-7544-47a1-b1d4-b1c327da6bd6"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 182510,
        "unexpected_percent": 38.218867987745504,
        "partial_unexpected_list": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        "partial_unexpected_counts": [
          {
            "value": null,
            "count": 20
          }
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "result_format": "COMPLETE",
          "batch_id": "postgres_datatourisme_database-datatourisme_data_table",
          "column": "uri_id_du_poi"
        },
        "meta": {},
        "id": "63ba37fd-bee4-43c7-816a-099e4358dd9a"
      },
      "result": {
        "element_count": 477539,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "completeness_suite",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 16,
    "successful_expectations": 10,
    "unsuccessful_expectations": 6,
    "success_percent": 62.5
  },
  "meta": {
    "great_expectations_version": "1.3.4",
    "batch_spec": {
      "type": "table",
      "data_asset_name": "datatourisme_data_table",
      "table_name": "raw.datatourisme_data",
      "schema_name": null,
      "batch_identifiers": {}
    },
    "batch_markers": {
      "ge_load_time": "20250205T125401.213814Z"
    },
    "active_batch_definition": {
      "datasource_name": "postgres_datatourisme_database",
      "data_connector_name": "fluent",
      "data_asset_name": "datatourisme_data_table",
      "batch_identifiers": {}
    },
    "validation_id": "99e1aba4-fd3b-459b-b8d0-e41c3b67a3a3",
    "checkpoint_id": null,
    "batch_parameters": null
  },
  "id": null
}
```

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: Linux Ubuntu
 - Great Expectations Version: 1.3.7
 - Data Source: Local PostgreSQL
 - Cloud environment: None

**Additional context**
