### ISSUE TITLE
Extra (not needed) SQL Query issued to a database when running a checkpoint

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#7450]
**Describe the bug**

Extra (not needed) full table SELECT issued to a database when running a checkpoint as a first SQL before all expected_to_be_issued_for_real_validations SQLs are run, 
only after you Turn OFF temp table creation,

SQL example:

```
SELECT * 
from public.customer_demographics 
```

**To Reproduce**

Detected on Snowflake, reproducible on a Snowflake trial account:

1) Turn OFF temp table creation in great_expectations.yml:

      class_name: SqlAlchemyExecutionEngine
      create_temp_table: False

2) run a checkpoint upon a SQL Select:

sample checkpoint:
```
name: test_checkpoint 
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: Full
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: sflake
      data_connector_name: default_runtime_data_connector_name
      data_asset_name: my_table_name
      runtime_parameters:
        query: "\nSELECT * \nfrom public.customer_demographics"
      batch_identifiers:
        default_identifier_name: default_identifier
    expectation_suite_name: sflake_suite
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```

sample expectation_suite:
```
{
  "data_asset_type": null,
  "expectation_suite_name": "sflake_suite",
  "expectations": [
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "cd_demo_sk"
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_values_to_be_between",
      "kwargs": {
        "column": "cd_purchase_estimate",
        "max_value": 3000,
        "min_value": 0
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "default_data_asset_name",
          "data_connector_name": "default_runtime_data_connector_name",
          "datasource_name": "sf_dev",
          "limit": 1000
        },
        "citation_date": "2023-03-23T15:06:56.714677Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.16.1"
  }
}
```

**Expected behavior**

No extra full table SELECTs issued

**Environment (please complete the following information):**
 - Operating System: Linux Ubuntu
 - Great Expectations Version: "0.16.1"
 - SQLAlchemy 1.4.46

**Additional info
before you Turn OFF temp table creation, the SQL issued would be like this (as expected):

CREATE OR REPLACE TEMPORARY TABLE ge_temp_b8f8eeae AS
SELECT * 
from public.customer_demographics
