### ISSUE TITLE
DataContext scans through all datasources even if only one is being used (yes, I'm back!)

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#7655]
**Describe the bug**
DataContext scans through all datasources even if only one is being used
Similar or same to https://github.com/great-expectations/great_expectations/issues/2241 

**To Reproduce**
add for example spark datasource to great_expectations.yml:
```

  spark_datasource:
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      class_name: SparkDFExecutionEngine
      module_name: great_expectations.execution_engine
    data_connectors:
      spark_data_connector:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - some_key_maybe_pipeline_stage
          - some_other_key_maybe_run_id


```
and run an Airflow DAG with GreatExpectationsOperator with checkpoint upon a different datasource (not spark_datasource!)

You will get this in Airflow DAG log:

 {{util.py:849}} ERROR - Unable to load spark context; install optional spark dependency for support.

 {{abstract_data_context.py:2992}} WARNING - Cannot initialize datasource spark_datasource: Cannot initialize datasource spark_datasource, error: SparkContext could not be started.

**Expected behavior**

only datasource needed for the checkpoint is initialized

**Environment (please complete the following information):**
 - Operating System: [Linux]
 - Great Expectations Version: [e.g. 0.16.1]
