### ISSUE TITLE
GX parses URN mentioned in evaluation parameter as string instead of its value

### ISSUE THREAD

**Issue by ramananayak** [great-expectations/great_expectations#7688]
**Describe the bug**
We create a parameter with its value being a URN in evaluation_parameter inside the checkpoint. When we use this parameter in expectation suite , the actual URN will be passed inside the suite as a string instead of actual URN value. and I can see the error `Provided max threshold must be a date-time (for datetime columns) or number`.

**To Reproduce**
1. create a expectation suite with one expectation (say 'v_user_table_warning_suite_4'). Example
```yaml
{
  "data_asset_type": null,
  "expectation_suite_name": "v_user_table_warning_suite_4",
  "expectations": [
    {
      "expectation_type": "expect_table_row_count_to_be_between",
      "kwargs": {
        "min_value": 200000,
        "max_value": 600000,
        "result_format": {
          "result_format": "COMPLETE"
        }
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.16.7"
  }
}
```
2. create a checkpoint and add a evaluation parameter say (upstream_row_count) and mention previous run validation URN to it. This checkpoint will include two batch request, where the validation result of first will be used in second.
```yaml
-- part of warning_checkpoint.yaml
evaluation_parameters:
  upstream_row_count: urn:great_expectations:validations:v_user_table_warning_suite_4:expect_table_row_count_to_be_between.result.observed_value
```
4. Create a expectation suite and assign this (upstream_row_count) to $PARAMETER inside any suite.
```json
-- my_schema.my_table.json
{
  "data_asset_type": null,
  "expectation_suite_name": "my_schema.my_table",
  "expectations": [
    {
      "expectation_type": "expect_table_row_count_to_be_between",
      "kwargs": {
        "max_value": {
          "$PARAMETER": "upstream_row_count"
        },
        "min_value": null
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.16.7"
  }
}
```
5. run the checkpoint from CLI. You will get an error. `Provided max threshold must be a date-time (for datetime columns) or number`
6. Or inside python environment call the context and upon running this checkpoint you can see above evaluation parameter is parsed as string. Instead of assigning its value

**Expected behavior**
upstream_row_count should read the value instead of URN string.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.7

**Additional context**
- I tested another way,by directly assigning the URN  to parameter in expectation suite. Its working as expected. So I think the issue is how GX is parsing the evaluation_parameter when URN is mentioned in the .yaml checkpoint file.
- [gx-community-support slack discussion](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1682015873064519)
