### ISSUE TITLE
Dots in names leads to Expectation Suite failures in Interactive mods

### ISSUE THREAD

**Issue by nenkie76** [great-expectations/great_expectations#8235]
**Describe the bug**

We'd like to organise suites into folders, each one representing a schema in the database. Suites and checkpoints are moved into subfolders `great_expectations/expectations/gold/fact_users/test.json` and have respective names like `gold.fact_users.test` with schema name `gold`.

`great_expectations.yml` file:
```
assets:
  gold.fact_users:
    class_name: Asset
    module_name: great_expectations.datasource.data_connector.asset
    schema_name: gold
    sampling_method: sample_using_a_list
    sampling_kwargs:
      column_name: id
      value_list: [ 10 ]
```

Expectation: `great_expectations/expectations/gold/fact_users/tests.json`

`"expectation_suite_name": "gold.fact_users.tests"`

Checkpoint: `great_expectations/checkpoints/gold/fact_users/tests.yml`

```
name: gold.fact_users.tests
....
  data_asset_name: gold.fact_users
expectation_suite_name: gold.fact_users.tests
```

The set-up with `.` looks like causing issues when locally running `great_expectations suite edit gold.fact_users.tests` Interactively and first Jupiter cell fails building proper object name, having doubled the `schema` name. 

```
ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002003 (42S02): SQL compilation error:
Object 'DB.GOLD."gold.fact_users"' does not exist or not authorized.
[SQL: CREATE OR REPLACE TEMPORARY TABLE ge_temp_ab2a607f AS SELECT * 
FROM gold."gold.fact_users" 
WHERE id IN (10)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

How do you organise the subfolders structure, or it is recommended to keep it flat? I do not observe this issue running it from Python.

**Environment (please complete the following information):**
 - Operating System: MacOS 
 - Great Expectations Version: airflow-provider-great-expectations = "0.2.6"
 - Datasource: Snowflake
 - Cloud environment: Airflow AWS (MWAA 2.4.3)
