### ISSUE TITLE
Error when running an expectation with `create_temp_table` is set to `False`

### ISSUE THREAD

**Issue by moatazelmohtaseb** [great-expectations/great_expectations#8325]
**Describe the bug**
In my current environment I want to run validations on an SQL data source (which is a PostgreSQL database), But as the database is a read-replica, I set the datasource config `create_temp_table` to `False` in order to avoid an error the was thrown when great-expectations tried to create a temp table. But I got a different error instead.

Note: the validation worked when it was a read/write instance of the database.

**To Reproduce**
datasource.py:
```
pg_datasource = context.sources.add_or_update_sql(
    name="test_datasource",
    connection_string=my_connection_string,
    create_temp_table=False,
)
query_asset = pg_datasource.add_query_asset(name="test_asset", query="SELECT id  FROM table")
```
Code:
```
data_asset = context.get_datasource("test_datasource").get_asset("test_asset")
expectation_suite_name = "test_suite"
batch_request = data_asset.build_batch_request(options={})
context.add_or_update_expectation_suite(expectation_suite_name)

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name,
)
expectation_validation_result2 = validator.expect_column_values_to_be_between(
    "order_id", 1,80
)
```
great_expectations.yml:
```
# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources: {}

# This config file supports variable substitution which enables: 1) keeping
# secrets out of source control & 2) environment-based configuration changes
# such as staging vs prod.
#
# When GX encounters substitution syntax (like `my_key: ${my_value}` or
# `my_key: $my_value`) in the great_expectations.yml file, it will attempt
# to replace the value of `my_key` with the value from an environment
# variable `my_value` or a corresponding key read from this config file,
# which is defined through the `config_variables_file_path`.
# Environment variables take precedence over variables defined here.
#
# Substitution values defined here can be a simple (non-nested) value,
# nested value such as a dictionary, or an environment variable (i.e. ${ENV_VAR})
#
#
# https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials


config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
#
# Three stores are required: expectations, validations, and
# evaluation_parameters, and must exist with a valid store entry. Additional
# stores can be configured for uses such as data_docs, etc.

  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: ff81e21f-6536-4bb5-aaff-11a149ca16a5
  enabled: true
fluent_datasources:
  test_datasource:
    type: sql
    assets:
      test_asset:
        type: query
        order_by: []
        batch_metadata: {}
        query: SELECT id AS order_id FROM orders
    connection_string: ${DB_URI}
    create_temp_table: false
include_rendered_content:
  expectation_suite: false
  globally: false
  expectation_validation_result: false
notebooks:

```
full stack trace:
```
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
File /usr/local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py:546, in ExecutionEngine._process_direct_and_bundled_metric_computation_configurations(self, metric_fn_direct_configurations, metric_fn_bundle_configurations)
    543 try:
    544     resolved_metrics[
    545         metric_computation_configuration.metric_configuration.id
--> 546     ] = metric_computation_configuration.metric_fn(  # type: ignore[misc] # F not callable
    547         **metric_computation_configuration.metric_provider_kwargs
    548     )
    549 except Exception as e:

File /usr/local/lib/python3.8/site-packages/great_expectations/expectations/metrics/metric_provider.py:50, in metric_value.<locals>.wrapper.<locals>.inner_func(*args, **kwargs)
     48 @wraps(metric_fn)
     49 def inner_func(*args, **kwargs):
---> 50     return metric_fn(*args, **kwargs)

File /usr/local/lib/python3.8/site-packages/great_expectations/expectations/metrics/table_metrics/table_column_types.py:71, in ColumnTypes._sqlalchemy(cls, execution_engine, metric_domain_kwargs, metric_value_kwargs, metrics, runtime_configuration)
     67     raise GreatExpectationsError(
     68         "the requested batch is not available; please load the batch into the execution engine."
     69     )
---> 71 return _get_sqlalchemy_column_metadata(execution_engine.engine, batch_data)

File /usr/local/lib/python3.8/site-packages/great_expectations/expectations/metrics/table_metrics/table_column_types.py:103, in _get_sqlalchemy_column_metadata(engine, batch_data)
    101     schema_name = batch_data.source_schema_name or batch_data.selectable.schema
--> 103 return get_sqlalchemy_column_metadata(
    104     engine=engine,
    105     table_selectable=table_selectable,
    106     schema_name=schema_name,
    107 )

File /usr/local/lib/python3.8/site-packages/great_expectations/expectations/metrics/util.py:356, in get_sqlalchemy_column_metadata(engine, table_selectable, schema_name)
    348 except (
    349     KeyError,
    350     AttributeError,
   (...)
    354     # we will get a KeyError for temporary tables, since
    355     # reflection will not find the temporary schema
--> 356     columns = column_reflection_fallback(
    357         selectable=table_selectable,
    358         dialect=engine.dialect,
    359         sqlalchemy_engine=engine,
    360     )
    362 # Use fallback because for mssql and trino reflection mechanisms do not throw an error but return an empty list

File /usr/local/lib/python3.8/site-packages/great_expectations/expectations/metrics/util.py:600, in column_reflection_fallback(selectable, dialect, sqlalchemy_engine)
    599     else:
--> 600         query = sa.select(sa.text("*")).select_from(selectable).limit(1)
    602 result_object = connection.execute(query)

File <string>:2, in select_from(self, *froms)

File /usr/local/lib/python3.8/site-packages/sqlalchemy/sql/base.py:283, in _generative.<locals>._generative(fn, self, *args, **kw)
    282 self = self._generate()
--> 283 x = fn(self, *args, **kw)
    284 assert x is self, "generative methods must return self"

File /usr/local/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py:6043, in Select.select_from(self, *froms)
   6009 r"""Return a new :func:`_expression.select` construct with the
   6010 given FROM expression(s)
   6011 merged into its list of FROM objects.
   (...)
   6040 
   6041 """
-> 6043 self._from_obj += tuple(
   6044     coercions.expect(
   6045         roles.FromClauseRole, fromclause, apply_propagate_attrs=self
   6046     )
   6047     for fromclause in froms
   6048 )
   6049 return self

File /usr/local/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py:6044, in <genexpr>(.0)
   6009 r"""Return a new :func:`_expression.select` construct with the
   6010 given FROM expression(s)
   6011 merged into its list of FROM objects.
   (...)
   6040 
   6041 """
   6043 self._from_obj += tuple(
-> 6044     coercions.expect(
   6045         roles.FromClauseRole, fromclause, apply_propagate_attrs=self
   6046     )
   6047     for fromclause in froms
   6048 )
   6049 return self

File /usr/local/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py:413, in expect(role, element, apply_propagate_attrs, argname, post_inspect, disable_inspection, **kw)
    412     if resolved is None:
--> 413         resolved = impl._literal_coercion(
    414             element, argname=argname, **kw
    415         )
    416 else:

File /usr/local/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py:619, in _NoTextCoercion._literal_coercion(self, element, argname, **kw)
    616 if isinstance(element, str) and issubclass(
    617     elements.TextClause, self._role_class
    618 ):
--> 619     _no_text_coercion(element, argname)
    620 else:

File /usr/local/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py:601, in _no_text_coercion(element, argname, exc_cls, extra, err)
    594 def _no_text_coercion(
    595     element: Any,
    596     argname: Optional[str] = None,
   (...)
    599     err: Optional[Exception] = None,
    600 ) -> NoReturn:
--> 601     raise exc_cls(
    602         "%(extra)sTextual SQL expression %(expr)r %(argname)sshould be "
    603         "explicitly declared as text(%(expr)r)"
    604         % {
    605             "expr": util.ellipses_string(element),
    606             "argname": "for argument %s" % (argname,) if argname else "",
    607             "extra": "%s " % extra if extra else "",
    608         }
    609     ) from err

ArgumentError: Textual SQL expression '%(139839236142800 anon)s' should be explicitly declared as text('%(139839236142800 anon)s')

The above exception was the direct cause of the following exception:

MetricResolutionError                     Traceback (most recent call last)
Cell In[10], line 1
----> 1 expectation_validation_result2 = validator.expect_column_values_to_be_between(
      2     "order_id", 1,80
      3 )
      5 # print(expectation_validation_result2)

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validator.py:597, in Validator.validate_expectation.<locals>.inst_expectation(*args, **kwargs)
    591         validation_result = ExpectationValidationResult(
    592             success=False,
    593             exception_info=exception_info,
    594             expectation_config=configuration,
    595         )
    596     else:
--> 597         raise err
    599 if self._include_rendered_content:
    600     validation_result.render()

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validator.py:560, in Validator.validate_expectation.<locals>.inst_expectation(*args, **kwargs)
    556     validation_result = ExpectationValidationResult(
    557         expectation_config=copy.deepcopy(expectation.configuration)
    558     )
    559 else:
--> 560     validation_result = expectation.validate(
    561         validator=self,
    562         evaluation_parameters=self._expectation_suite.evaluation_parameters,
    563         data_context=self._data_context,
    564         runtime_configuration=basic_runtime_configuration,
    565     )
    567 # If validate has set active_validation to true, then we do not save the config to avoid
    568 # saving updating expectation configs to the same suite during validation runs
    569 if self._active_validation is True:

File /usr/local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1276, in Expectation.validate(self, validator, configuration, evaluation_parameters, interactive_evaluation, data_context, runtime_configuration)
   1267 self._warn_if_result_format_config_in_expectation_configuration(
   1268     configuration=configuration
   1269 )
   1271 configuration.process_evaluation_parameters(
   1272     evaluation_parameters, interactive_evaluation, data_context
   1273 )
   1274 expectation_validation_result_list: list[
   1275     ExpectationValidationResult
-> 1276 ] = validator.graph_validate(
   1277     configurations=[configuration],
   1278     runtime_configuration=runtime_configuration,
   1279 )
   1280 return expectation_validation_result_list[0]

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validator.py:1072, in Validator.graph_validate(self, configurations, runtime_configuration)
   1070         return evrs
   1071     else:
-> 1072         raise err
   1074 configuration: ExpectationConfiguration
   1075 result: ExpectationValidationResult

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validator.py:1051, in Validator.graph_validate(self, configurations, runtime_configuration)
   1044 resolved_metrics: Dict[Tuple[str, str, str], MetricValue]
   1046 try:
   1047     (
   1048         resolved_metrics,
   1049         evrs,
   1050         processed_configurations,
-> 1051     ) = self._resolve_suite_level_graph_and_process_metric_evaluation_errors(
   1052         graph=graph,
   1053         runtime_configuration=runtime_configuration,
   1054         expectation_validation_graphs=expectation_validation_graphs,
   1055         evrs=evrs,
   1056         processed_configurations=processed_configurations,
   1057         show_progress_bars=self._determine_progress_bars(),
   1058     )
   1059 except Exception as err:
   1060     # If a general Exception occurs during the execution of "ValidationGraph.resolve()", then
   1061     # all expectations in the suite are impacted, because it is impossible to attribute the failure to a metric.
   1062     if catch_exceptions:

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validator.py:1210, in Validator._resolve_suite_level_graph_and_process_metric_evaluation_errors(self, graph, runtime_configuration, expectation_validation_graphs, evrs, processed_configurations, show_progress_bars)
   1202 resolved_metrics: Dict[Tuple[str, str, str], MetricValue]
   1203 aborted_metrics_info: Dict[
   1204     Tuple[str, str, str],
   1205     Dict[str, Union[MetricConfiguration, Set[ExceptionInfo], int]],
   1206 ]
   1207 (
   1208     resolved_metrics,
   1209     aborted_metrics_info,
-> 1210 ) = self._metrics_calculator.resolve_validation_graph(
   1211     graph=graph,
   1212     runtime_configuration=runtime_configuration,
   1213     min_graph_edges_pbar_enable=0,
   1214 )
   1216 # Trace MetricResolutionError occurrences to expectations relying on corresponding malfunctioning metrics.
   1217 rejected_configurations: List[ExpectationConfiguration] = []

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/metrics_calculator.py:283, in MetricsCalculator.resolve_validation_graph(self, graph, runtime_configuration, min_graph_edges_pbar_enable)
    278 resolved_metrics: Dict[Tuple[str, str, str], MetricValue]
    279 aborted_metrics_info: Dict[
    280     Tuple[str, str, str],
    281     Dict[str, Union[MetricConfiguration, Set[ExceptionInfo], int]],
    282 ]
--> 283 resolved_metrics, aborted_metrics_info = graph.resolve(
    284     runtime_configuration=runtime_configuration,
    285     min_graph_edges_pbar_enable=min_graph_edges_pbar_enable,
    286     show_progress_bars=self._show_progress_bars,
    287 )
    288 return resolved_metrics, aborted_metrics_info

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py:206, in ValidationGraph.resolve(self, runtime_configuration, min_graph_edges_pbar_enable, show_progress_bars)
    200 resolved_metrics: Dict[Tuple[str, str, str], MetricValue] = {}
    202 # updates graph with aborted metrics
    203 aborted_metrics_info: Dict[
    204     Tuple[str, str, str],
    205     Dict[str, Union[MetricConfiguration, Set[ExceptionInfo], int]],
--> 206 ] = self._resolve(
    207     metrics=resolved_metrics,
    208     runtime_configuration=runtime_configuration,
    209     min_graph_edges_pbar_enable=min_graph_edges_pbar_enable,
    210     show_progress_bars=show_progress_bars,
    211 )
    213 return resolved_metrics, aborted_metrics_info

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py:312, in ValidationGraph._resolve(self, metrics, runtime_configuration, min_graph_edges_pbar_enable, show_progress_bars)
    308                 failed_metric_info[failed_metric.id]["exception_info"] = {
    309                     exception_info
    310                 }
    311     else:
--> 312         raise err
    313 except Exception as e:
    314     if catch_exceptions:

File /usr/local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py:282, in ValidationGraph._resolve(self, metrics, runtime_configuration, min_graph_edges_pbar_enable, show_progress_bars)
    277         computable_metrics.add(metric)
    279 try:
    280     # Access "ExecutionEngine.resolve_metrics()" method, to resolve missing "MetricConfiguration" objects.
    281     metrics.update(
--> 282         self._execution_engine.resolve_metrics(
    283             metrics_to_resolve=computable_metrics,
    284             metrics=metrics,
    285             runtime_configuration=runtime_configuration,
    286         )
    287     )
    288     progress_bar.update(len(computable_metrics))
    289     progress_bar.refresh()

File /usr/local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py:281, in ExecutionEngine.resolve_metrics(self, metrics_to_resolve, metrics, runtime_configuration)
    272 metric_fn_bundle_configurations: List[MetricComputationConfiguration]
    273 (
    274     metric_fn_direct_configurations,
    275     metric_fn_bundle_configurations,
   (...)
    279     runtime_configuration=runtime_configuration,
    280 )
--> 281 return self._process_direct_and_bundled_metric_computation_configurations(
    282     metric_fn_direct_configurations=metric_fn_direct_configurations,
    283     metric_fn_bundle_configurations=metric_fn_bundle_configurations,
    284 )

File /usr/local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py:550, in ExecutionEngine._process_direct_and_bundled_metric_computation_configurations(self, metric_fn_direct_configurations, metric_fn_bundle_configurations)
    544         resolved_metrics[
    545             metric_computation_configuration.metric_configuration.id
    546         ] = metric_computation_configuration.metric_fn(  # type: ignore[misc] # F not callable
    547             **metric_computation_configuration.metric_provider_kwargs
    548         )
    549     except Exception as e:
--> 550         raise gx_exceptions.MetricResolutionError(
    551             message=str(e),
    552             failed_metrics=(
    553                 metric_computation_configuration.metric_configuration,
    554             ),
    555         ) from e
    557 try:
    558     # an engine-specific way of computing metrics together
    559     resolved_metric_bundle: Dict[
    560         Tuple[str, str, str], MetricValue
    561     ] = self.resolve_metric_bundle(
    562         metric_fn_bundle=metric_fn_bundle_configurations
    563     )

MetricResolutionError: Textual SQL expression '%(139839236142800 anon)s' should be explicitly declared as text('%(139839236142800 anon)s')
```

**Expected behavior**
`validator` should be able to run on the read replica if `create_temp_table: false`

**Environment (please complete the following information):**
 - Operating System: docker-image:python:3.8 running on Ubuntu 20.04
 - Great Expectations Version: 0.17.4
 - Datasource: PostgreSQL
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]
