### ISSUE TITLE
expect_column_sum_to_be_between expectation fails even when the observed value is within the min & max range

### ISSUE THREAD

**Issue by Ranji-1712** [great-expectations/great_expectations#8330]
**Describe the bug**
For validating the column sum value , used the expectation type "expect_column_sum_to_be_between" with the min_value & max_value . The min_value & max_value are passed as a parameter ( result of the query configured in the query store ) . Even though the observed_value is with the min & max range the validation fails . below are the code / configs used ..

**To Reproduce**

**great_expectations.yml file :** 

```
datasources:
  lake_prod_data_source:
    name: lake_data_source
    class_name: Datasource
    module_name: great_expectations.datasource
    data_connectors:
      lake_prod_data_connector:
        class_name: ConfiguredAssetSqlDataConnector
        assets:
          luna_lazypay_transactions_data_asset:
            schema_name: luna_lazypay
            table_name: transactions
    execution_engine:
      module_name: great_expectations.execution_engine
      create_temp_table: false
      class_name: SqlAlchemyExecutionEngine
      connection_string: ${lake_prod_connection_string}
config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
  # Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
#
# Three stores are required: expectations, validations, and
# evaluation_parameters, and must exist with a valid store entry. Additional
# stores can be configured for uses such as data_docs, etc.

#luna_lazypay.transactions
  sqlalchemy_query_store:
    class_name: SqlAlchemyQueryStore
    credentials:
      connection_string: ${lake_prod_connection_string}
    queries:
      amount_column_sum_value_source:
        query: select sum(amount) as sum_of_amount from lake_lazypay.transactions
          where datecreated < cast(current_date as timestamp) - interval '330' minute
          --data till previous day 18:30 UTC
        return_type: scalar

  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    store_backend_parameters:
      class_name: TupleStoreBackend
      base_directory: uncommitted/config_variables/
      prefix: "parameters"
      sep: "__"
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: 20556d2a-71ce-4407-b376-2085a8454936
  enabled: true
include_rendered_content:
  expectation_suite: false
  expectation_validation_result: false
  globally: false
```

Batch_Request : 

```
my_batch_request = BatchRequest(
    datasource_name="lake_prod_data_source",
    data_connector_name="lake_prod_data_connector",
    data_asset_name="luna_lazypay_transactions_data_asset",
)


validator = context.get_validator(
    batch_request=my_batch_request
)
validator.head()
```

Validation : 

```
aggregate_value_validation_result = validator.expect_column_sum_to_be_between(
    column= 'amount',
    min_value = {"$PARAMETER": "urn:great_expectations:stores:sqlalchemy_query_store:amount_column_sum_value_source"},
    max_value = {"$PARAMETER": "urn:great_expectations:stores:sqlalchemy_query_store:amount_column_sum_value_source"},
)
print(aggregate_value_validation_result)
```

**Validation Result :** 

```
{
  "expectation_config": {
    "kwargs": {
      "column": "amount",
      "min_value": 340539760273.52637,
      "max_value": 340539760273.5264,
      "batch_id": "c1d3935673b855f4456a21b1945a4b83"
    },
    "meta": {},
    "expectation_type": "expect_column_sum_to_be_between"
  },
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 340539760273.5239
  },
  "success": false,
  "meta": {}
}
```

**Expected behavior**
If the observed_value is within the min & max range also considering the precision value, then the validation should pass

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.13
 - Datasource: Athena/SQL
