### ISSUE TITLE
Assets of type query not working for Oracle datasource

### ISSUE THREAD

**Issue by hjannasch** [great-expectations/great_expectations#8618]
**Describe the bug**
As our database stack if mainly Oracle based. I tried to setup an expectation suite using a fluent oracledb sql datasource, but using assets of type 'query' it not working.
Well I know you are not supporting Oracle officially, but do you have any idea on this?

**To Reproduce**
```
fluent_datasources:
  dm:
    type: sql
    assets:
      anrede:
        type: table
        order_by: []
        batch_metadata: {}
        table_name: anrede
        schema_name:
      person_query:
        type: query
        order_by: []
        batch_metadata: {}
        query: select * from PERSON
    connection_string: oracle+oracledb://<user>:<pwd>@localhost:1521/xe`
```

The table asset works fine, but the query asset generates a none valid SQL.
When the person_query asset is used to create a new validator and suite:
```
import great_expectations as gx

context = gx.get_context()
data_asset = context.get_datasource("dm").get_asset("person_query")
batch_request = data_asset.build_batch_request()

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name="nat_query_expectation_suite",
)
validator.head()
```
This leads to the error:
DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00907: missing right parenthesis
[SQL: CREATE GLOBAL TEMPORARY TABLE gx_temp_5da3476a ON COMMIT PRESERVE ROWS AS SELECT * 
FROM (SELECT * from PERSON FROM DUAL) anon_1 
WHERE 1 = 1]

**Expected behavior**
Generate valid SQL, it looks like ... FROM DUAL is too much here.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.17.12
 - Data Source: SQL (Oracle with oracledb driver)

great-expectations==0.17.12
sqlalchemy==2.0.20
oracledb==1.4.0

**Comment by hjannasch** [comment]
Here is the trace.
[traceback.log](https://github.com/great-expectations/great_expectations/files/12436216/traceback.log)

**Comment by Kilo59** [comment]
@hjannasch You can try changing the value of `create_temp_table = False` when defining the Datasource but I suspect you'll still end up with some version of a bad identifier issue when you run a checkpoint.

Please report back if this does or doesn't work.

```yaml
fluent_datasources:
  dm:
    type: sql
    create_temp_table: false
    assets:
      anrede:
        type: table
        order_by: []
        batch_metadata: {}
        table_name: anrede
        schema_name:
      person_query:
        type: query
        order_by: []
        batch_metadata: {}
        query: select * from PERSON
    connection_string: oracle+oracledb://<user>:<pwd>@localhost:1521/xe`
```
