### ISSUE TITLE
Environment variable not replaced in great_expectations.yml

### ISSUE THREAD

**Issue by skamalj** [great-expectations/great_expectations#8987]
**Describe the bug**
I am trying to use environment variable in great_expectations.yml to set column_name and table_name from environment variable. 
This replacement is only working for connection_string but not in any other place. Is this expected behavior? As per documentation it should replace every such instance in yaml file.
```yaml
      my_asset:
        type: table
        order_by: []
        batch_metadata: {}
        splitter:
          column_name: $dept
          method_name: split_on_column_value
        table_name: $table
        schema_name:
```

**To Reproduce**
Use aboue config with any sql source

**Expected behavior**
Replace the variables in yaml configuration

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.18.1
 - Data Source: Snowflake
 - Cloud environment: local

**Additional context**
