### ISSUE TITLE
Having create_temp_table = False on MS SQL Server produces error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#9186]
**Describe the bug**
Having create_temp_table = False in  great_expectations.yml on MS SQL Server produces error:
'NoneType' object is not iterable

this error with Traceback below is rendered in DataDocs for every expectation:

Traceback (most recent call last):
File "/home/user/Documents/fldr/.venv/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 546, in _process_direct_and_bundled_metric_computation_configurations
] = metric_computation_configuration.metric_fn( # type: ignore[misc] # F not callable
File "/home/user/Documents/fldr/.venv/lib/python3.10/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 50, in inner_func
return metric_fn(*args, **kwargs)
File "/home/user/Documents/fldr/.venv/lib/python3.10/site-packages/great_expectations/expectations/metrics/table_metrics/table_columns.py", line 42, in _sqlalchemy
return [col["name"] for col in column_metadata]
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/user/Documents/fldr/.venv/lib/python3.10/site-packages/great_expectations/validator/validation_graph.py", line 282, in _resolve
self._execution_engine.resolve_metrics(
File "/home/user/Documents/fldr/.venv/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 281, in resolve_metrics
return self._process_direct_and_bundled_metric_computation_configurations(
File "/home/user/Documents/fldr/.venv/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 550, in _process_direct_and_bundled_metric_computation_configurations
raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: 'NoneType' object is not iterable

**To Reproduce**

1) add "create_temp_table: False" key to great_expectations.yml, e.g.:

```yaml
datasources:
  mssql_12345:
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      create_temp_table: False
      connection_string: mssql+pyodbc://${db_user}:${db_pwd}@${db_hostport}/${db_name}?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes
      module_name: great_expectations.execution_engine
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
```

 run your checkpoint and see 'NoneType' object is not iterable error in DataDocs
 
 2) remove / comment out "create_temp_table: False" key in great_expectations.yml 
 - your checkpoint and Datadocs work fine

**Expected behavior**
"create_temp_table: False" key is handled without errors

**Environment (please complete the following information):**
 - Operating System: Ubuntu 22.04
 - Great Expectations Version: tried 0.17.4, 0.18.4 and latest = 0.18.7
 - Data Source: local MS SQL Express in same Ubuntu, tried SQLAlchemy==1.4.9, 2.0 and latest
 - Cloud environment: local Ubuntu
