### ISSUE TITLE
Nested dicts within ExpectationSuiteValidationResult are no SerializableDictDot

### ISSUE THREAD

**Issue by MarcelBeining** [great-expectations/great_expectations#9250]
**Describe the bug**
I wanted to use the EmailAction to send an email using a validation result returned by `context.get_validation_result` but the renderer tries to access a value within the validation result using dot notation (as the validation result is inherited from SerializableDictDot) but it is a simple dictionary: `validation_result.meta["active_batch_definition"].data_asset_name`

So I would guess one of the following classes/methods has a bug:
- The method `get_validation_result` by not transforming the information under meta into dictdot classes
- The class `ExpectationSuiteValidationResult` by not transforming the information under meta into dictdot classes
- The `EmailRenderer` by trying to access the key "data_asset_name" with dot notation although it should be accessed via dict key.

**To Reproduce**
*great_expectations.yml config*

```
# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources: {}

config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
#
# Three stores are required: expectations, validations, and
# evaluation_parameters, and must exist with a valid store entry. Additional
# stores can be configured for uses such as data_docs, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: XXXXX
  enabled: true
notebooks:
include_rendered_content:
  globally: false
  expectation_suite: false
  expectation_validation_result: false
fluent_datasources:
  kedro_pandas_in_memory_datasource:
    type: pandas
    assets:
      companies:
        type: dataframe
        batch_metadata: {}
```

_Executed code:_
```
import great_expectations as ge
from great_expectations.render.renderer import EmailRenderer


ge_context = ge.get_context()
validation_result = ge_context.get_validation_result(
                SUITE_NAME, run_id=RUN_ID
            )
EmailRenderer().render(validation_result)
```

_Error Traceback_

> Traceback (most recent call last):
>   File "Code\kedro-expectations\venv\lib\site-packages\click\core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "Code\kedro-expectations\venv\lib\site-packages\click\core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "Code\kedro-expectations\venv\lib\site-packages\click\core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "Code\kedro-expectations\venv\lib\site-packages\kedro\framework\cli\project.py", line 224, in run
>     session.run(
>   File "Code\kedro-expectations\venv\lib\site-packages\kedro\framework\session\session.py", line 406, in run
>     hook_manager.hook.after_pipeline_run(
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_hooks.py", line 433, in __call__
>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_manager.py", line 418, in traced_hookexec
>     return outcome.get_result()
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_result.py", line 108, in get_result
>     raise exc.with_traceback(exc.__traceback__)
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_result.py", line 70, in from_call
>     result = func()
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_manager.py", line 415, in <lambda>
>     lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_callers.py", line 116, in _multicall
>     raise exception.with_traceback(exception.__traceback__)
>   File "Code\kedro-expectations\venv\lib\site-packages\pluggy\_callers.py", line 80, in _multicall
>     res = hook_impl.function(*args)
>   File "code\kedro-expectations\kedro_expectations\kedro_expectations.py", line 147, in after_pipeline_run
>     EmailRenderer.render(validation_result)
>   File "Code\kedro-expectations\venv\lib\site-packages\great_expectations\checkpoint\actions.py", line 100, in run
>     return self._run(
>   File "Code\kedro-expectations\venv\lib\site-packages\great_expectations\checkpoint\actions.py", line 813, in _run
>     title, html = self.renderer.render(
>   File Code\kedro-expectations\venv\lib\site-packages\great_expectations\render\renderer\email_renderer.py", line 38, in render
>     if validation_result.meta["active_batch_definition"].data_asset_name
> AttributeError: 'dict' object has no attribute 'data_asset_name'
> python-BaseException
> 

**Expected behavior**
The EmailRenderer should simply render the content of the validation result.

**Environment (please complete the following information):**
 - Operating System: Windows64
 - Great Expectations Version: 0.18.4
 - Data Source: fluent Pandas
 - Cloud environment: None
