### ISSUE TITLE
Bad format(type Error)  with function json.dump()

### ISSUE THREAD

**Issue by ejlm1988** [great-expectations/great_expectations#9457]
**Describe the bug**
In the executions, an error message appears stating that the log with the information could not be loaded, because the data has not been formatted correctly.

Return error -> TypeError: not all arguments converted during string formatting

The file great_expectations.yml is the next:

```yaml
config_version: 3.0

datasources:
  mysql_datasource:
    data_connectors:
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        name: default_runtime_data_connector_name
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
      default_inferred_data_connector_name:
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
        name: default_inferred_data_connector_name
        class_name: InferredAssetSqlDataConnector
    module_name: great_expectations.datasource
    execution_engine:
      connection_string: **connection db**
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      create_temp_table: false
    name: mysql_datasource
    class_name: Datasource
  bigquery_datasource:
    data_connectors:
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
      default_inferred_data_connector_name:
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
        class_name: InferredAssetSqlDataConnector
    module_name: great_expectations.datasource
    execution_engine:
      connection_string: **connection db json**
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      create_temp_table: false
    class_name: Datasource

config_variables_file_path: uncommitted/config_variables.yml

plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: 4bf1545b-0773-4230-b5c8-f13f6afff4f8
  enabled: true
notebooks:
include_rendered_content:
  expectation_suite: false
  expectation_validation_result: false
  globally: false
```

**Expected behavior**
I hope you don't get the error that the log information could not be formatted.

**Environment (please complete the following information):**
  - No LSB modules are available.
  - Distributor ID: Ubuntu
  - Description:    Ubuntu 20.04.4 LTS
  - Release:        20.04
  Codename:       focal
